### ISSUE TITLE
一个丢失的nginx 编译过程Dockerfile文件

### ISSUE THREAD

**Issue by Allen-yan** [xddxdd/dockerfiles#1]
你好，在这篇文章里
https://lantian.pub/article/modify-website/nginx-ldap-authentication.lantian/
有一个关于nginx ldap-auth 模块的编译过程的Dockerfile 文件 
https://github.com/xddxdd/dockerfiles/blob/master/nginx/Dockerfile.amd64
现在已经404 了。 不知道你还有没有印象。

我现在在nginx 里配置ldap-auth 发现一直没有成功， 希望能看看相关编译过程。

多谢

**Comment by xddxdd** [comment]
你可以参考这份文件：https://github.com/xddxdd/dockerfiles/blob/210f0f82c7bc1c0c3697d329b73ea31abea6b14a/nginx/Dockerfile

但是后续使用中我发现 ldap 模块不是很稳定，已经将它替换掉了。

**Comment by Allen-yan** [comment]
我最近也在用 发现了一些很奇怪的现象，成功认证一次后，发现不管怎么重启都能认证成功，过了很长一段时间后，又需要认证。

后来发现和nginx 的配置有关，但感觉没找到根源。这个模块的确是有点问题。

你说的不稳定时什么， 用什么替换了？ 另外那个需要额外后端的ldap模块嘛？

**Comment by xddxdd** [comment]
我当时遇到的情况是经常会认证失败。我后来放弃了 LDAP，改用了 Keycloak+oauth2-proxy。
https://github.com/oauth2-proxy/oauth2-proxy

**Comment by Allen-yan** [comment]
好的 多谢！
